### ISSUE TITLE
Install results in ERROR 500

### ISSUE THREAD

**Issue by Hotte512** [shyim/ShyimPluginManager#2]
I tried to require autoload.php withhout the DIR constant like ../../vendor/etc... but for some reasone it's not working.
It works if i require it with a static path like: require('/var/www/vhosts/domain.de/httpdocs/vendor/autoload.php');

Due to my low coding skills, may be I missed something...

APACHE ERROR LOG:
mod_fcgid: stderr: PHP Fatal error: require(): Failed opening required '/var/www/vhosts/domain.de/httpdocs/custom/plugins/ShyimPluginManager/vendor/autoload.php' (include_path='/var/www/vhosts/domain.de/httpdocs/engine/Library:.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/domain.de/httpdocs/custom/plugins/ShyimPluginManager/ShyimPluginManager.php on line 9

might it be a problem with my server settings?
(atm i don't think so because there should be more relative references in shopware)

KIND REGARDS

And by the way THANK YOU FOR SO MUCH GREAT WORK @Shyim !!

**Comment by shyim** [comment]
I guess you have installed it without composer :)
Can you run inside the plugin directory composer install ?

**Comment by Hotte512** [comment]
you got me!
I did not install it with composer.. just uploaded it to SW-Plugin Manager ;)

THX
